load "code/database_code/example.m";
QQ := Rationals();
C;
KC<x,y> := FunctionField(C);
KC_alg := AlgorithmicFunctionField(KC);
F;
R<x,y> := Parent(F);
k := RationalFunctionField(QQ);
Rk<Y> := PolynomialRing(k);
F_func := Evaluate(F,[k.1,Y]);
K_func := FunctionField(F_func);
MinimalPolynomial(K_func.1);
EvaluateCoefficients(F,[1/k.1]);
min_y := MinimalPolynomial(K_func.1);
min_y;
cs := Coefficients(min_y);
cs_new := [Evaluate(el,1/k.1) : el in cs];
min_y_new := &+[cs_new[i]*Y^(i-1) : i in [1..#cs_new]];
min_y_new;
F_new := 2^20*min_y_new;
Evaluate(F_new,[Y/2^5]);
R<Y> := Parent(F_new);
F_new := Evaluate(F_new,Y/2^5);
